client_config_backend: settings
client_config:
  client_id: [add client id]
  client_secret: [add client secret]

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.metadata
  - https://www.googleapis.com/auth/drive.file